# Site
repository: pcorrick/pcorrick.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Phil Corrick
title: Telecommunications Engineer and Project Manager
email: phil@corrick.xyz
website: phil.corrick.xyz

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username: pcorrick
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: philcorrick
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Download Resume
  icon: fas fa-download
  url: https://phil.corrick.xyz/download/resume-oct21.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/phil_2021.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a telecommunications engineer and project manager with over 15 years of professional experience, currently based in Perth, Westen Australia.

  I have extensive experience successfully delivering complex software, integration and technology infrastructure projects, coordinating with teams of technical and non-technical people across various time zones. I have a broad spectrum of experience in the mining, oil & gas, critical infrastructure and telecommunications industries.

  I enjoy working with a team to solve difficult problems and deliver complex solutions.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Gibson Quai International
        link: www.gqi.com.au
        # link_text: boringcompany.com
        sub_title: WA Regional Manager
        caption: January 2022 - Present
        quote: >
          Gibson Quai International provides independent, expert advice on all aspects of telecommunications industry technology, services and management.
        description: | # this will include new lines to allow paragraphs
            Consulting service delivery and business development in Perth, Western Australia.

      - layout: left
        title: Cardiac Rhythm Connect
        link: www.cardiacrc.com.au
        # link_text: boringcompany.com
        sub_title: Chief Technology Officer
        caption: January 2020 - Present
        quote: >
          CRC is committed to helping patients understand the therapy they are receiving and applying our specialised knowledge of device programming in order to ensure every patient has their device tailored specifically for their needs & lifestyle.
        description: | # this will include new lines to allow paragraphs
            Strategic management and software development of the underlying technology stack to run a modern, efficient medical data and services business.

              * Web application development of customer facing applications in use by medical practices and service providers <mark>PHP</mark>, <mark>Vue.js</mark>, <mark>Laravel</mark>
              * Design and management of cloud infrastructure <mark>AWS</mark>
              * Database administration and development <mark>mysql</mark>
              * Payment gateway integration <mark>Stripe</mark>
              * Automation of patient communications

      - layout: left
        title: Western Advance
        link: www.westernadvance.com.au
        # link_text: boringcompany.com
        sub_title: Project Manager and Systems Engineer
        caption: November 2013 - January 2022
        quote: >
          Western Advance specialises in electronic security, surveillance and threat detection solutions.  We partner recognised industry leaders to provide complete solutions to complex problems throughout Australia and the Asia Pacific region.
        description: | # this will include new lines to allow paragraphs
          Project management and systems engineering of integrated solutions, combining technology from multiple vendors and manufacturers, primarily in the oil & gas sector.

          Specification, testing and management of custom software solutions for integration between disparate systems.

          Implementation of operational technology solutions, and interfacing between operatinal technology (OT) and information technology (IT) systems.

          Specific technology experience with:
            * Electronic access control and site e-mustering systems including: <mark>Lenel OnGuard</mark>, <mark>Gallagher</mark>, <mark>Integriti</mark>, <mark>Tecom</mark> and <mark>Facility Commander</mark>
            * CCTV hardware and software from manufacturers including: <mark>Synectics</mark>, <mark>Avigilon</mark>, <mark>Genetec</mark>, <mark>Milestone</mark>, <mark>Geutebruck</mark>, <mark>Axis</mark>, <mark>Bosch</mark>, <mark>Hikvision</mark>, <mark>BriefCam</mark>, <mark>AnyVision</mark>
            * Physical Security Information Management systems (<mark>Everbridge Control Center</mark>)
            * <mark>Industronic</mark> Public Address and General Alarm systems
            * <mark>Navtech</mark> 77GHz FMCW radar solutions for vehicle and personnel tracking and outdoor surveillance

      - layout: left
        title: UXC Connect
        link: https://dxc.com/au/en
        # link_text: boringcompany.com
        sub_title: Project Manager
        caption: November 2010 - November 2013
        description: | # this will include new lines to allow paragraphs
          Project Manager for communications and entertainment system delivery to 6000+ rooms at mining camps across the Pilbara for FMG, Rio Tinto and Chevron/Gorgon. Responsible for the successful delivery of all aspects of each project in conjunction with the technical delivery team.

          Technology solutions delivered include optical fibre cabling and passive splitting infrastructure, satellite receive system, GPON, IPTV, telephony and Internet access delivery.

      - layout: left
        title: Analysys Mason
        sub_title: Consultant
        caption: January 2009 - July 2009
        description: | # this will include new lines to allow paragraphs
            * Integration test witness for an emergency services TETRA radio network in the UK, including handset features, dispatch software and resilient integration of systems.
            * Process development, contract management assistance and monitoring for the Irish National Broadband Scheme.

      - layout: left
        title: Gibson Quai - AAS
        sub_title: Telecommunications Engineer
        caption: December 2004 - November 2010
        description: | # this will include new lines to allow paragraphs
            * Preparation of specifications, scoping of contractor works, technical drawings and procurement documentation for telecommunications facilities for a large LNG project. Including telecoms towers, equipment shelters, structured cabling systems, fire detection and alarm, building cabling and public address systems.
            * Management of a small team for the design and specification of communications facilities for a number of remote mining villages. Including IP telephony, Ethernet network, hybrid fibre/coaxial TV distribution, fibre-to-the-buildling (GPON) and structured cabling systems.
            * Radio broadcast planning and advice for community and high power open narrowcasting services in Western Australia.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Western Australia
        caption: 2000 - 2004
        sub_title: BEng (Electrical and Electronic Engineering) & BSc (Computer Science)
        description: | # this will include new lines to allow paragraphs
          Bachelor of Engineering (electrical and electronic engineering) and Bachelor of Science (Computer Science)
          Final year engineering project *Influence of Phase and Timing Offsets on Soft Decoding Algorithms*

      - layout: left
        title: University of Bristol
        caption: 2003
        description: | # this will include new lines to allow paragraphs
          I spent an academic year on the Study Abroad program at Bristol University, studying Electrical and Electronic Engineering.

      - layout: left
        title: Central Institute of Technology
        caption: 2008 - 2010
        sub_title: Certificate IV, Applied Language (Spanish)
        description: | # this will include new lines to allow paragraphs
          

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my other interests and hobbies are:
      - Swimming, cycling and running: Swimrun and Triathlon
      - Building Raspberry Pi projects
      - Squash
      - Fremantle Dockers

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
